# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Verilog-projects/design_1/ip/design_1_seven_seg_0_2/design_1_seven_seg_0_2.xci
# IP: The module: 'design_1_seven_seg_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Verilog-projects/design_1/ip/design_1_seven_seg_0_2/constraints/seven_seg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_seven_seg_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Verilog-projects/design_1/ip/design_1_seven_seg_0_2/design_1_seven_seg_0_2.xci
# IP: The module: 'design_1_seven_seg_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Verilog-projects/design_1/ip/design_1_seven_seg_0_2/constraints/seven_seg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_seven_seg_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
