# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Verilog-projects/Nexys-A7-100T-Master.xdc

# Block Designs: D:/Verilog-projects/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: D:/Verilog-projects/design_1/ip/design_1_clk_seg_seven_0_0/design_1_clk_seg_seven_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_seg_seven_0_0 || ORIG_REF_NAME==design_1_clk_seg_seven_0_0} -quiet] -quiet

# IP: D:/Verilog-projects/design_1/ip/design_1_seven_seg_0_2/design_1_seven_seg_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_seven_seg_0_2 || ORIG_REF_NAME==design_1_seven_seg_0_2} -quiet] -quiet

# XDC: D:/Verilog-projects/design_1/design_1_ooc.xdc
